name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" 
  flutter: 3.10.3 

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3
  flutter_svg: ^2.0.7
  intl: ^0.18.1  
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon/group1.svg
    - lib/assets/icon/group2.svg
    - lib/assets/icon/group3.svg
    - lib/assets/icon/ava.png

  
